tasks:
  - init: npm install
    command: >
      npm i -g @angular/cli &&
      gp sync-done gp &&
      ng analytics off &&
      npm i -g json-server &&
      json-server --watch db.json
  - command: >
      npm i -g nodemon &&
      nodemon server.js
  - command: >
      gp sync-await ng &&
      ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
