tasks:
  - before: npm i -g @angular/cli &&
            ng analytics off
    init: npm install
    # command: >
      # npm i -g @angular/cli &&
      # gp sync-done gp &&
      # ng analytics off &&
    command: >
      npm i -g json-server &&
      json-server --watch db.json &&
      gp sync-done do-express
  - command: >
      gp sync-await do-express &&
      npm i -g nodemon &&
      nodemon server.js &&
      go sync-done do-node
  - command: >
      gp sync-await do-node &&
      ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
