# tasks:
#   - init: npm install && npm run build
#     command: npm run start
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addLabel: prebuild-in-gitpod

tasks:
  - init: npm install
    command: npm i -g @angular/angular-cli
    command: ng analytics off
    command: ng serve --host 0.0.0.0 --disable-host-check
    command: nodemon server.js
    command: json-server --watch db.json

ports:
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-browser

