github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    addCheck: false
    addComment: false
    addLabel: prebuild-in-gitpod

tasks:
  - before: ng analytics off &&
            npm i -g @angular/cli                       
    init: ng analytics off && 
          npm install
    command: >
      npm i -g json-server &&
      json-server --watch db.json
  - command: >
      gp await-port 3000 &&
      npm i -g nodemon &&
      nodemon server.js
  - command: >
      gp await-port 8000 &&
      ng serve

ports:
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
